backend:
  name: git-gateway
  branch: main # o master según tu repositorio

media_folder: "images/uploads" # Carpeta donde se guardarán las fotos
public_folder: "/images/uploads"

collections:
  - name: "inmuebles"
    label: "Inmuebles"
    folder: "inmuebles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Precio", name: "price", widget: "string" }
      - { label: "Ubicación", name: "location", widget: "string" }
      - { label: "Imagen principal", name: "thumbnail", widget: "image" }
      - { label: "Galería de imágenes", name: "gallery", widget: "list", field: { label: Imagen, name: image, widget: image } }
