backend:
  name: github
  repo: gleiberrivasrah/inmueblesrah
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "listings"
    label: "Inmuebles"
    folder: "data"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "titulo", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Tipo", name: "tipo", widget: "select", options: ["venta","alquiler"] }
      - { label: "Precio USD", name: "precioUSD", widget: "number" }
      - { label: "Ubicación", name: "ubicacion", widget: "object", fields: 
          [{ label: "Municipio", name: "municipio", widget: "string" },
           { label: "Urbanización", name: "urbanizacion", widget: "string" }] }
      - { label: "Metros", name: "metros", widget: "number" }
      - { label: "Habitaciones", name: "habitaciones", widget: "number" }
      - { label: "Baños", name: "banos", widget: "number" }
      - { label: "Puestos", name: "estacionamientos", widget: "number" }
      - { label: "Hab de servicio", name: "hab_servicio", widget: "number" }
      - { label: "Baño de servicio", name: "bano_servicio", widget: "number" }
      - { label: "Descripción", name: "descripcion", widget: "text" }
      - { label: "Amenities", name: "amenities", widget: "list" }
      - { label: "Imágenes", name: "imagenes", widget: "list", allow_add: true, field: { label: "Imagen", name: "image", widget: "image" } }
      - { label: "Link único", name: "link", widget: "string" }
